wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.20.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1750622030
    t:
      1:
      - 1
      - 41
      3:
      - 4
      - 13
      - 16
      - 42
      - 55
      4: 3.10.14
      5: 0.20.1
      13: linux-x86_64
model:
  desc: null
  value:
    architecture: alexnet_test
    pretrained: true
    weights_path: /dataset/pretrained_weights/alexnet_weights.pth
    input_channels: 3
    num_classes_rot: 5
    num_classes_trans: 5
    output_dir: /tmp_log/
dataset:
  desc: null
  value:
    root_dir: /dataset/
    context_len: 10
    horizon: 5
    batch_size: 32
    num_workers: 4
    feature_dim: 3
    dataset_dict:
      train:
        euroc:
        - MH_01_easy
        - MH_03_medium
        - MH_04_difficult
        - MH_05_difficult
        - V1_01_easy
        - V1_03_difficult
        - V2_01_easy
        - V2_02_medium
        - V2_03_difficult
      val:
        euroc:
        - MH_02_easy
        - V1_02_medium
data_transforms:
  desc: null
  value:
    resize:
    - 224
    - 224
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
optimization:
  desc: null
  value:
    optimizer: adamw
    lr: 0.001
    weight_decay: 0.01
    momentum: 0.9
training:
  desc: null
  value:
    task: classification
    loss_function: CrossEntropyLoss
    num_epochs: 25
    eval_period: 1
    print_period: 10
    save_model_period: 5
    save_statistics_period: 5
misc:
  desc: null
  value:
    seed: 42
    use_wandb: true
    wandb_project: ood-slam
    wandb_entity: udem-mila
    log_dir: /tmp_log/
    exp_id: 0
    exp_name: euroc_test_experiment
    verbose: true
