experiment_name: 'euroc_test_experiment'

# Model parameters
model:
  architecture: 'alexnet_test' # Model architecture: alexnet, resnet18, resnet34, etc.
  pretrained: true        
  weights_path: '/dataset/pretrained_weights/alexnet_weights.pth'   
  input_channels: 3       # Number of input channels (e.g., 3 for RGB, 6 for stereo)
  num_outputs: [5, 5]     # Number of outputs: e.g., 3 for rotation, 5 for translation
  output_dir: '/final_log/'          

# Dataset parameters
dataset:
  root_dir: '/dataset/'
  context_len: 10
  horizon: 5               
  batch_size: 32                                                                       
  num_workers: 4                        
  feature_dim: 3                                                                                                            

# Data augmentation and transformation parameters
data_transforms:
  resize: [224, 224]                   
  mean: [0.485, 0.456, 0.406]          
  std: [0.229, 0.224, 0.225]            

# Training Parameters
training:
  task: 'classification'                
  loss_function: 'EMDSquaredLoss'       
  optimizer: 'Adam'                     
  learning_rate_groups:
    pretrained_lr: 0.0001
    new_lr: 0.001
  weight_decay: 0.0001                
  num_epochs: 25                       

# Logging Parameters
logging:
  use_wandb: false                      
  wandb_project: 'ood-slam'           
  wandb_entity: 'udem-mila'         
  log_interval: 10                      